image: docker:20.10.16

stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

before_script:
  - cd gitlab-ci
  - docker info
#  - bundle install

services:
  - docker:20.10.16-dind


branch review:
  stage: build
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

echo_job:
  stage: build
  script:
    - echo $name
    - echo $url

build_job:
  stage: build
  script:
    - docker build -t reddit-app ./docker-reddit
    - docker run -p 9292:9292 reddit-app
