image: docker:20.10.16

stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

before_script:
  - cd gitlab-ci
  - docker info
#  - bundle install

services:
  - docker:20.10.16-dind

build_job:
  stage: build
  script:
    - docker build -t reddit-app ./docker-reddit
    - docker run -p 9292:9292 reddit-app
