---
- hosts: docker
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: install python modules for docker
      pip:
        name: docker

    - name: docker start
      service:
        name: docker
        state: started
        enabled: yes

    - debug:
        var: hostvars['docker-app-0'].ansible_host

    - name: gitlab-ce
      docker_container:
        name: gitlab-ce
        state: started
        image: "gitlab/gitlab-ce:latest"
        pull: true
        env:
          GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://{{hostvars['docker-app-0'].ansible_host}}'
        ports:
          - "80:80"
          - "443:443"
          - "2222:22"
        volumes:
          - '/srv/gitlab/config:/etc/gitlab'
          - '/srv/gitlab/logs:/var/log/gitlab'
          - '/srv/gitlab/data:/var/opt/gitlab'
        restart_policy: always

    - name: gitlab-runner2
      docker_container:
        name: gitlab-runner2
        state: started
        image: "gitlab/gitlab-runner:latest"
        pull: true
        volumes:
          - '/srv/gitlabrunner/config:/etc/gitlab-runner'
          - '/var/run/docker.sock:/var/run/docker.sock'
        restart_policy: always

    - name: Register gitlab-runner2
      shell: "docker exec -it gitlab-runner2 gitlab-runner register \
               --url http://{{hostvars['docker-app-0'].ansible_host}}/ \
               --non-interactive \
               --locked=false \
               --name DockerRunner \
               --executor docker \
               --docker-image alpine:latest \
               --registration-token YOUR_TOKEN_GITLAB \
               --tag-list 'linux,xenial,ubuntu,docker' \
               --run-untagged"

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
