Vagrant.configure("2") do |config|

#   config.ssh.private_key_path = ["~/.ssh/appuser", "~/.vagrant.d/insecure_private_key"]
#   config.vm.provision "file", source: "~/.ssh/appuser.pub", destination: "~/.ssh/authorized_keys"
#
#   config.ssh.username = 'vagrant'
#   config.ssh.password = 'vagrant'
#   config.ssh.insert_key = false
#   config.vm.provision "shell", inline: <<-SHELL
#      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
#      systemctl restart sshd.service
#   SHELL


  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "192.168.56.2"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "db" => ["dbserver"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "192.168.56.3"
  end
end
